# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/poissonbreaker/Escritorio/FEM/UI/MainApp4.3.ui'
#
# Created: Sun Jul  3 15:59:27 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from DomainSpecificLayout import Layout
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 630)
        MainWindow.setMinimumSize(QtCore.QSize(649, 630))
        MainWindow.setMaximumSize(QtCore.QSize(649, 630))
        self.centralwidget = Layout(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Visualization = QtGui.QWidget()
        self.Visualization.setObjectName("Visualization")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Visualization)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.viz_FE_Sol = FE_Viz(self.Visualization)
        self.viz_FE_Sol.setObjectName("viz_FE_Sol")
        self.verticalLayout_3.addWidget(self.viz_FE_Sol)
        self.tabWidget.addTab(self.Visualization, "")
        self.Configuration = QtGui.QWidget()
        self.Configuration.setObjectName("Configuration")
        self.viz_ODE_eq = Eq_Viz(self.Configuration)
        self.viz_ODE_eq.setGeometry(QtCore.QRect(9, 9, 591, 141))
        self.viz_ODE_eq.setObjectName("viz_ODE_eq")
        self.Wizard = QtGui.QStackedWidget(self.Configuration)
        self.Wizard.setGeometry(QtCore.QRect(40, 160, 551, 231))
        self.Wizard.setObjectName("Wizard")
        self.Space_Conf = QtGui.QWidget()
        self.Space_Conf.setObjectName("Space_Conf")
        self.Button_Next_to_Final = QtGui.QCommandLinkButton(self.Space_Conf)
        self.Button_Next_to_Final.setGeometry(QtCore.QRect(450, 110, 71, 31))
        self.Button_Next_to_Final.setObjectName("Button_Next_to_Final")
        self.Frame_Space_Conf = QtGui.QFrame(self.Space_Conf)
        self.Frame_Space_Conf.setGeometry(QtCore.QRect(160, 30, 231, 191))
        self.Frame_Space_Conf.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frame_Space_Conf.setFrameShadow(QtGui.QFrame.Raised)
        self.Frame_Space_Conf.setObjectName("Frame_Space_Conf")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Frame_Space_Conf)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolBox = QtGui.QToolBox(self.Frame_Space_Conf)
        self.toolBox.setStyleSheet("\n"
"background-color: rgb(246, 246, 246);")
        self.toolBox.setObjectName("toolBox")
        self.Domain = QtGui.QWidget()
        self.Domain.setGeometry(QtCore.QRect(0, 0, 211, 109))
        self.Domain.setObjectName("Domain")
        self.verticalLayout = QtGui.QVBoxLayout(self.Domain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout_a = QtGui.QHBoxLayout()
        self.Layout_a.setObjectName("Layout_a")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_a.addItem(spacerItem)
        self.label_Domain_L = QtGui.QLabel(self.Domain)
        self.label_Domain_L.setMinimumSize(QtCore.QSize(8, 30))
        self.label_Domain_L.setMaximumSize(QtCore.QSize(8, 30))
        self.label_Domain_L.setObjectName("label_Domain_L")
        self.Layout_a.addWidget(self.label_Domain_L)
        spacerItem1 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.Layout_a.addItem(spacerItem1)
        self.input_Domain_L = QtGui.QLineEdit(self.Domain)
        self.input_Domain_L.setMinimumSize(QtCore.QSize(51, 27))
        self.input_Domain_L.setMaximumSize(QtCore.QSize(51, 27))
        self.input_Domain_L.setObjectName("input_Domain_L")
        self.Layout_a.addWidget(self.input_Domain_L)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_a.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.Layout_a)
        self.Layout_b = QtGui.QHBoxLayout()
        self.Layout_b.setObjectName("Layout_b")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_b.addItem(spacerItem3)
        self.label_Domain_R = QtGui.QLabel(self.Domain)
        self.label_Domain_R.setMinimumSize(QtCore.QSize(9, 33))
        self.label_Domain_R.setMaximumSize(QtCore.QSize(9, 33))
        self.label_Domain_R.setObjectName("label_Domain_R")
        self.Layout_b.addWidget(self.label_Domain_R)
        spacerItem4 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.Layout_b.addItem(spacerItem4)
        self.input_Domain_R = QtGui.QLineEdit(self.Domain)
        self.input_Domain_R.setMinimumSize(QtCore.QSize(51, 27))
        self.input_Domain_R.setMaximumSize(QtCore.QSize(51, 27))
        self.input_Domain_R.setObjectName("input_Domain_R")
        self.Layout_b.addWidget(self.input_Domain_R)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_b.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.Layout_b)
        self.toolBox.addItem(self.Domain, "")
        self.Boundary = QtGui.QWidget()
        self.Boundary.setGeometry(QtCore.QRect(0, 0, 211, 109))
        self.Boundary.setObjectName("Boundary")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Boundary)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Layout_X0 = QtGui.QHBoxLayout()
        self.Layout_X0.setObjectName("Layout_X0")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_X0.addItem(spacerItem6)
        self.label_valX0 = QtGui.QLabel(self.Boundary)
        self.label_valX0.setMinimumSize(QtCore.QSize(72, 32))
        self.label_valX0.setMaximumSize(QtCore.QSize(72, 32))
        self.label_valX0.setObjectName("label_valX0")
        self.Layout_X0.addWidget(self.label_valX0)
        spacerItem7 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.Layout_X0.addItem(spacerItem7)
        self.input_valX0 = QtGui.QLineEdit(self.Boundary)
        self.input_valX0.setMinimumSize(QtCore.QSize(51, 27))
        self.input_valX0.setMaximumSize(QtCore.QSize(51, 27))
        self.input_valX0.setObjectName("input_valX0")
        self.Layout_X0.addWidget(self.input_valX0)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_X0.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.Layout_X0)
        self.Layout_XN = QtGui.QHBoxLayout()
        self.Layout_XN.setObjectName("Layout_XN")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_XN.addItem(spacerItem9)
        self.label_valXN = QtGui.QLabel(self.Boundary)
        self.label_valXN.setMinimumSize(QtCore.QSize(73, 31))
        self.label_valXN.setMaximumSize(QtCore.QSize(73, 31))
        self.label_valXN.setObjectName("label_valXN")
        self.Layout_XN.addWidget(self.label_valXN)
        spacerItem10 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.Layout_XN.addItem(spacerItem10)
        self.input_valXN = QtGui.QLineEdit(self.Boundary)
        self.input_valXN.setMinimumSize(QtCore.QSize(51, 27))
        self.input_valXN.setMaximumSize(QtCore.QSize(51, 27))
        self.input_valXN.setObjectName("input_valXN")
        self.Layout_XN.addWidget(self.input_valXN)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_XN.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.Layout_XN)
        self.toolBox.addItem(self.Boundary, "")
        self.verticalLayout_7.addWidget(self.toolBox)
        self.Wizard.addWidget(self.Space_Conf)
        self.NElems_Conf = QtGui.QWidget()
        self.NElems_Conf.setObjectName("NElems_Conf")
        self.Button_to_Start = QtGui.QCommandLinkButton(self.NElems_Conf)
        self.Button_to_Start.setGeometry(QtCore.QRect(450, 110, 71, 31))
        self.Button_to_Start.setObjectName("Button_to_Start")
        self.Frame_NElem_Conf = QtGui.QFrame(self.NElems_Conf)
        self.Frame_NElem_Conf.setGeometry(QtCore.QRect(100, 70, 311, 95))
        self.Frame_NElem_Conf.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frame_NElem_Conf.setFrameShadow(QtGui.QFrame.Raised)
        self.Frame_NElem_Conf.setObjectName("Frame_NElem_Conf")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.Frame_NElem_Conf)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Layout_NElems = QtGui.QHBoxLayout()
        self.Layout_NElems.setObjectName("Layout_NElems")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_NElems.addItem(spacerItem12)
        self.label_NofElems = QtGui.QLabel(self.Frame_NElem_Conf)
        self.label_NofElems.setObjectName("label_NofElems")
        self.Layout_NElems.addWidget(self.label_NofElems)
        spacerItem13 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.Layout_NElems.addItem(spacerItem13)
        self.NofElems_viz = QtGui.QLineEdit(self.Frame_NElem_Conf)
        self.NofElems_viz.setMinimumSize(QtCore.QSize(81, 27))
        self.NofElems_viz.setMaximumSize(QtCore.QSize(81, 27))
        self.NofElems_viz.setObjectName("NofElems_viz")
        self.Layout_NElems.addWidget(self.NofElems_viz)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Layout_NElems.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.Layout_NElems.addItem(spacerItem15)
        self.verticalLayout_8.addLayout(self.Layout_NElems)
        self.solve = QtGui.QPushButton(self.Frame_NElem_Conf)
        self.solve.setObjectName("solve")
        self.verticalLayout_8.addWidget(self.solve)
        self.Wizard.addWidget(self.NElems_Conf)
        self.Functions_Conf = QtGui.QWidget()
        self.Functions_Conf.setObjectName("Functions_Conf")
        self.Button_Next_to_params = QtGui.QCommandLinkButton(self.Functions_Conf)
        self.Button_Next_to_params.setGeometry(QtCore.QRect(450, 110, 71, 31))
        self.Button_Next_to_params.setObjectName("Button_Next_to_params")
        self.Frame_Functions_Conf = QtGui.QFrame(self.Functions_Conf)
        self.Frame_Functions_Conf.setGeometry(QtCore.QRect(80, 40, 331, 171))
        self.Frame_Functions_Conf.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Frame_Functions_Conf.setFrameShadow(QtGui.QFrame.Raised)
        self.Frame_Functions_Conf.setObjectName("Frame_Functions_Conf")
        self.groupBox = QtGui.QGroupBox(self.Frame_Functions_Conf)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 331, 201))
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(70, 40, 192, 101))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_fx = QtGui.QLabel(self.layoutWidget)
        self.label_fx.setObjectName("label_fx")
        self.horizontalLayout_2.addWidget(self.label_fx)
        self.input_fx = QtGui.QLineEdit(self.layoutWidget)
        self.input_fx.setObjectName("input_fx")
        self.horizontalLayout_2.addWidget(self.input_fx)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_px = QtGui.QLabel(self.layoutWidget)
        self.label_px.setObjectName("label_px")
        self.horizontalLayout.addWidget(self.label_px)
        self.input_px = QtGui.QLineEdit(self.layoutWidget)
        self.input_px.setObjectName("input_px")
        self.horizontalLayout.addWidget(self.input_px)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_qx = QtGui.QLabel(self.layoutWidget)
        self.label_qx.setObjectName("label_qx")
        self.horizontalLayout_3.addWidget(self.label_qx)
        self.input_qx = QtGui.QLineEdit(self.layoutWidget)
        self.input_qx.setObjectName("input_qx")
        self.horizontalLayout_3.addWidget(self.input_qx)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.Wizard.addWidget(self.Functions_Conf)
        self.line = QtGui.QFrame(self.Configuration)
        self.line.setGeometry(QtCore.QRect(-3, 150, 631, 20))
        self.line.setMinimumSize(QtCore.QSize(631, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_3 = QtGui.QGroupBox(self.Configuration)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 410, 191, 94))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Progress_conf = QtGui.QProgressBar(self.groupBox_3)
        self.Progress_conf.setProperty("value", 24)
        self.Progress_conf.setObjectName("Progress_conf")
        self.verticalLayout_6.addWidget(self.Progress_conf)
        self.Button_restart = QtGui.QPushButton(self.groupBox_3)
        self.Button_restart.setObjectName("Button_restart")
        self.verticalLayout_6.addWidget(self.Button_restart)
        self.line_2 = QtGui.QFrame(self.Configuration)
        self.line_2.setGeometry(QtCore.QRect(0, 390, 631, 20))
        self.line_2.setMinimumSize(QtCore.QSize(631, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.Configuration, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.viz_MSE = QtGui.QLineEdit(self.centralwidget)
        self.viz_MSE.setObjectName("viz_MSE")
        self.verticalLayout_2.addWidget(self.viz_MSE)
        MainWindow.setCentralWidget(self.centralwidget)
        self.bar_Prog_Conf = QtGui.QStatusBar(MainWindow)
        self.bar_Prog_Conf.setObjectName("bar_Prog_Conf")
        MainWindow.setStatusBar(self.bar_Prog_Conf)
        self.actionX = QtGui.QAction(MainWindow)
        self.actionX.setCheckable(True)
        self.actionX.setObjectName("actionX")
        self.actionGetr = QtGui.QAction(MainWindow)
        self.actionGetr.setObjectName("actionGetr")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.Wizard.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
         
        self.centralwidget.setParent(self)
        
        QtCore.QObject.connect(self.Button_Next_to_Final, QtCore.SIGNAL("clicked()"), self.centralwidget.Change_Tab)
        QtCore.QObject.connect(self.Button_Next_to_params, QtCore.SIGNAL("clicked()"), self.centralwidget.Change_Tab)
        QtCore.QObject.connect(self.Button_to_Start, QtCore.SIGNAL("clicked()"), self.centralwidget.Change_Tab)
        QtCore.QObject.connect(self.solve, QtCore.SIGNAL("clicked()"), self.centralwidget.Solve)
        QtCore.QObject.connect(self.Button_restart, QtCore.SIGNAL("clicked()"), self.centralwidget.CleanAll)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visualization), QtGui.QApplication.translate("MainWindow", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_Next_to_Final.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Domain_L.setText(QtGui.QApplication.translate("MainWindow", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Domain_R.setText(QtGui.QApplication.translate("MainWindow", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Domain), QtGui.QApplication.translate("MainWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_valX0.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Value at x<span style=\" vertical-align:sub;\">0</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_valXN.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Value at x<span style=\" vertical-align:sub;\">N</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Boundary), QtGui.QApplication.translate("MainWindow", "Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_to_Start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NofElems.setText(QtGui.QApplication.translate("MainWindow", "Number of elements", None, QtGui.QApplication.UnicodeUTF8))
        self.solve.setText(QtGui.QApplication.translate("MainWindow", "Solve", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_Next_to_params.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Functions ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fx.setText(QtGui.QApplication.translate("MainWindow", "f(x)=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_px.setText(QtGui.QApplication.translate("MainWindow", "p(x)=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_qx.setText(QtGui.QApplication.translate("MainWindow", "q(x)=", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration Process", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_restart.setText(QtGui.QApplication.translate("MainWindow", "Restart", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Configuration), QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "MSE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGetr.setText(QtGui.QApplication.translate("MainWindow", "Getr", None, QtGui.QApplication.UnicodeUTF8))

from VisualizationEngine import Eq_Viz, FE_Viz

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
